version: '2'
services:
  zookeeper:
    image: docker-registry-default.internal.elx.ohoy.io/masterly/zookeeper:v3.4.13
    ports:
      - "2181:2181"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper

  kafka-rest:
    image: confluentinc/cp-kafka-rest
    ports:
      - "8082:8082"
    links:
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: localhost
      KAFKA_REST_DEBUG: "true"

  kafka:
    hostname: localhost
    image: docker-registry-default.internal.elx.ohoy.io/masterly/kafka:v2.1.1-5
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper

  kafka-connect:
    image: docker-registry-default.internal.elx.ohoy.io/masterly/kafka-connect-s3:spreadfast-0.5.0bn-2
    links:
      - kafka
    environment:
      OVERRIDE_BROKERS: "kafka:9092"
      BUCKET: ___BUCKET___
      AWS_ACCESS_KEY_ID: ___AWS_ACCESS_KEY_ID___
      AWS_SECRET_ACCESS_KEY: ___AWS_SECRET_ACCESS_KEY___
